name: Static Website CI

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  lint-build:
    name: Lint and Validate HTML/CSS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint HTML files
        uses: Cyb3r-Jak3/htmlhint-action@v1.0.0
        with:
          files: "src/**/*.html"

      - name: Lint CSS files
        run: |
          npx stylelint "src/css/**/*.css" 