name: Development CI

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  lint-build-test:
    name: Lint, Build, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (for future linters or builds)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Basic HTML Lint (Very Basic Rules)
        run: |
          echo "Running basic HTML lint (non-blocking)..."
          npm install -g htmlhint
          echo '{
            "tag-pair": true,
            "doctype-first": false,
            "attr-lowercase": false,
            "attr-value-double-quotes": false,
            "spec-char-escape": false
          }' > .htmlhintrc.json
          htmlhint src/*.html || echo "Lint warnings ignored for now."

      - name: Build Placeholder
        run: echo "Building the project..."

      - name: Test Placeholder
        run: echo "Running tests..."

      - name: CI Completed
        run: echo "CI pipeline completed successfully!"
